// <auto-generated />
using System;
using LowCortisol.Platform.API.Shared.Infrastructure.Persistence.EntityFrameworkCore.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LowCortisol.Platform.API.Shared.Infrastructure.Persistence.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LowCortisol.Platform.API.DeviceControl.Domain.Model.Aggregates.DeviceCommand", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CommandType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("command_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DeviceGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_group_id");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<DateTime?>("ExecutedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_at");

                    b.Property<DateTime?>("FailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at");

                    b.Property<string>("FailureReason")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("failure_reason");

                    b.Property<Guid?>("IncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("reason");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasColumnName("requested_by");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("ValveId")
                        .HasColumnType("uuid")
                        .HasColumnName("valve_id");

                    b.HasKey("Id")
                        .HasName("p_k_device_commands");

                    b.HasIndex("CommandType")
                        .HasDatabaseName("i_x_device_commands_command_type");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("i_x_device_commands_created_at");

                    b.HasIndex("DeviceGroupId")
                        .HasDatabaseName("i_x_device_commands_device_group_id");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("i_x_device_commands_device_id");

                    b.HasIndex("IncidentId")
                        .HasDatabaseName("i_x_device_commands_incident_id");

                    b.HasIndex("RequestedAt")
                        .HasDatabaseName("i_x_device_commands_requested_at");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("i_x_device_commands_room_id");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("i_x_device_commands_site_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("i_x_device_commands_status");

                    b.HasIndex("ValveId")
                        .HasDatabaseName("i_x_device_commands_valve_id");

                    b.ToTable("device_commands", (string)null);
                });

            modelBuilder.Entity("LowCortisol.Platform.API.DeviceControl.Domain.Model.Aggregates.ValveOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DeviceGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_group_id");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<DateTime?>("FailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at");

                    b.Property<string>("FailureReason")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("failure_reason");

                    b.Property<Guid?>("IncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<string>("PreviousStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("previous_status");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("reason");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("resource_type");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<string>("TargetStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("target_status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("ValveId")
                        .HasColumnType("uuid")
                        .HasColumnName("valve_id");

                    b.HasKey("Id")
                        .HasName("p_k_valve_operations");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("i_x_valve_operations_created_at");

                    b.HasIndex("DeviceGroupId")
                        .HasDatabaseName("i_x_valve_operations_device_group_id");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("i_x_valve_operations_device_id");

                    b.HasIndex("IncidentId")
                        .HasDatabaseName("i_x_valve_operations_incident_id");

                    b.HasIndex("Reason")
                        .HasDatabaseName("i_x_valve_operations_reason");

                    b.HasIndex("RequestedAt")
                        .HasDatabaseName("i_x_valve_operations_requested_at");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("i_x_valve_operations_room_id");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("i_x_valve_operations_site_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("i_x_valve_operations_status");

                    b.HasIndex("ValveId")
                        .HasDatabaseName("i_x_valve_operations_valve_id");

                    b.ToTable("valve_operations", (string)null);
                });

            modelBuilder.Entity("LowCortisol.Platform.API.DeviceControl.Domain.Model.Entities.CommandAuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(520)
                        .HasColumnType("character varying(520)")
                        .HasColumnName("description");

                    b.Property<Guid>("DeviceCommandId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_command_id");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("performed_at");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasColumnName("performed_by");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_command_audit_entries");

                    b.HasIndex("Action")
                        .HasDatabaseName("i_x_command_audit_entries_action");

                    b.HasIndex("DeviceCommandId")
                        .HasDatabaseName("i_x_command_audit_entries_device_command_id");

                    b.HasIndex("PerformedAt")
                        .HasDatabaseName("i_x_command_audit_entries_performed_at");

                    b.ToTable("command_audit_entries", (string)null);
                });

            modelBuilder.Entity("LowCortisol.Platform.API.DeviceControl.Domain.Model.Entities.CommandExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DeviceCommandId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_command_id");

                    b.Property<string>("FailureReason")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("failure_reason");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("ResultMessage")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("result_message");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_command_executions");

                    b.HasIndex("DeviceCommandId")
                        .HasDatabaseName("i_x_command_executions_device_command_id");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("i_x_command_executions_started_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("i_x_command_executions_status");

                    b.ToTable("command_executions", (string)null);
                });

            modelBuilder.Entity("LowCortisol.Platform.API.DeviceControl.Domain.Model.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DeviceGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_group_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("serial_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_devices");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("i_x_devices_created_at");

                    b.HasIndex("DeviceGroupId")
                        .HasDatabaseName("i_x_devices_device_group_id");

                    b.HasIndex("SerialNumber")
                        .IsUnique()
                        .HasDatabaseName("i_x_devices_serial_number");

                    b.HasIndex("Status")
                        .HasDatabaseName("i_x_devices_status");

                    b.HasIndex("Type")
                        .HasDatabaseName("i_x_devices_type");

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("LowCortisol.Platform.API.DeviceControl.Domain.Model.Entities.Sensor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<decimal?>("LastReadingValue")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("last_reading_value");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("resource_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_sensors");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("i_x_sensors_created_at");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("i_x_sensors_device_id");

                    b.HasIndex("ResourceType")
                        .HasDatabaseName("i_x_sensors_resource_type");

                    b.HasIndex("Status")
                        .HasDatabaseName("i_x_sensors_status");

                    b.ToTable("sensors", (string)null);
                });

            modelBuilder.Entity("LowCortisol.Platform.API.DeviceControl.Domain.Model.Entities.Valve", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("resource_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_valves");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("i_x_valves_created_at");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("i_x_valves_device_id");

                    b.HasIndex("ResourceType")
                        .HasDatabaseName("i_x_valves_resource_type");

                    b.HasIndex("Status")
                        .HasDatabaseName("i_x_valves_status");

                    b.ToTable("valves", (string)null);
                });

            modelBuilder.Entity("LowCortisol.Platform.API.Monitoring.Domain.Model.Entities.Anomaly", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("description");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at");

                    b.Property<Guid>("DeviceGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_group_id");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<decimal>("LimitValue")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("limit_value");

                    b.Property<Guid>("ReadingId")
                        .HasColumnType("uuid")
                        .HasColumnName("reading_id");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("resource_type");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("uuid")
                        .HasColumnName("sensor_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("severity");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<Guid>("ThresholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("threshold_id");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("Value")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("p_k_anomalies");

                    b.HasIndex("DetectedAt")
                        .HasDatabaseName("i_x_anomalies_detected_at");

                    b.HasIndex("DeviceGroupId")
                        .HasDatabaseName("i_x_anomalies_device_group_id");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("i_x_anomalies_device_id");

                    b.HasIndex("ReadingId")
                        .HasDatabaseName("i_x_anomalies_reading_id");

                    b.HasIndex("ResourceType")
                        .HasDatabaseName("i_x_anomalies_resource_type");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("i_x_anomalies_room_id");

                    b.HasIndex("SensorId")
                        .HasDatabaseName("i_x_anomalies_sensor_id");

                    b.HasIndex("Severity")
                        .HasDatabaseName("i_x_anomalies_severity");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("i_x_anomalies_site_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("i_x_anomalies_status");

                    b.ToTable("anomalies", (string)null);
                });

            modelBuilder.Entity("LowCortisol.Platform.API.Monitoring.Domain.Model.Entities.ConsumptionReading", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DeviceGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_group_id");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("resource_type");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("uuid")
                        .HasColumnName("sensor_id");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("Value")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("p_k_consumption_readings");

                    b.HasIndex("CapturedAt")
                        .HasDatabaseName("i_x_consumption_readings_captured_at");

                    b.HasIndex("DeviceGroupId")
                        .HasDatabaseName("i_x_consumption_readings_device_group_id");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("i_x_consumption_readings_device_id");

                    b.HasIndex("ResourceType")
                        .HasDatabaseName("i_x_consumption_readings_resource_type");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("i_x_consumption_readings_room_id");

                    b.HasIndex("SensorId")
                        .HasDatabaseName("i_x_consumption_readings_sensor_id");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("i_x_consumption_readings_site_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("i_x_consumption_readings_status");

                    b.ToTable("consumption_readings", (string)null);
                });

            modelBuilder.Entity("LowCortisol.Platform.API.Monitoring.Domain.Model.Entities.Threshold", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DeviceGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_group_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal>("LimitValue")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("limit_value");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("operator");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("resource_type");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<Guid?>("SensorId")
                        .HasColumnType("uuid")
                        .HasColumnName("sensor_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("severity");

                    b.Property<Guid?>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_thresholds");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("i_x_thresholds_created_at");

                    b.HasIndex("DeviceGroupId")
                        .HasDatabaseName("i_x_thresholds_device_group_id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("i_x_thresholds_is_active");

                    b.HasIndex("ResourceType")
                        .HasDatabaseName("i_x_thresholds_resource_type");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("i_x_thresholds_room_id");

                    b.HasIndex("SensorId")
                        .HasDatabaseName("i_x_thresholds_sensor_id");

                    b.HasIndex("Severity")
                        .HasDatabaseName("i_x_thresholds_severity");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("i_x_thresholds_site_id");

                    b.ToTable("thresholds", (string)null);
                });

            modelBuilder.Entity("LowCortisol.Platform.API.Notification.Domain.Model.Aggregates.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_at");

                    b.Property<Guid?>("AnomalyId")
                        .HasColumnType("uuid")
                        .HasColumnName("anomaly_id");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DeviceGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_group_id");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<Guid?>("ReadingId")
                        .HasColumnType("uuid")
                        .HasColumnName("reading_id");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("resource_type");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("uuid")
                        .HasColumnName("sensor_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("severity");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("source_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_alerts");

                    b.HasIndex("AnomalyId")
                        .HasDatabaseName("i_x_alerts_anomaly_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("i_x_alerts_created_at");

                    b.HasIndex("DeviceGroupId")
                        .HasDatabaseName("i_x_alerts_device_group_id");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("i_x_alerts_device_id");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("i_x_alerts_room_id");

                    b.HasIndex("SensorId")
                        .HasDatabaseName("i_x_alerts_sensor_id");

                    b.HasIndex("Severity")
                        .HasDatabaseName("i_x_alerts_severity");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("i_x_alerts_site_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("i_x_alerts_status");

                    b.ToTable("alerts", (string)null);
                });

            modelBuilder.Entity("LowCortisol.Platform.API.Notification.Domain.Model.Aggregates.Incident", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AlertId")
                        .HasColumnType("uuid")
                        .HasColumnName("alert_id");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(640)
                        .HasColumnType("character varying(640)")
                        .HasColumnName("description");

                    b.Property<Guid>("DeviceGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_group_id");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("priority");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("uuid")
                        .HasColumnName("sensor_id");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_incidents");

                    b.HasIndex("AlertId")
                        .HasDatabaseName("i_x_incidents_alert_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("i_x_incidents_created_at");

                    b.HasIndex("DeviceGroupId")
                        .HasDatabaseName("i_x_incidents_device_group_id");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("i_x_incidents_device_id");

                    b.HasIndex("Priority")
                        .HasDatabaseName("i_x_incidents_priority");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("i_x_incidents_room_id");

                    b.HasIndex("SensorId")
                        .HasDatabaseName("i_x_incidents_sensor_id");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("i_x_incidents_site_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("i_x_incidents_status");

                    b.ToTable("incidents", (string)null);
                });

            modelBuilder.Entity("LowCortisol.Platform.API.Notification.Domain.Model.Aggregates.NotificationChannel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_notification_channels");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("i_x_notification_channels_created_at");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("i_x_notification_channels_is_active");

                    b.HasIndex("Type")
                        .HasDatabaseName("i_x_notification_channels_type");

                    b.ToTable("notification_channels", (string)null);
                });

            modelBuilder.Entity("LowCortisol.Platform.API.Notification.Domain.Model.Entities.AlertDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AlertId")
                        .HasColumnType("uuid")
                        .HasColumnName("alert_id");

                    b.Property<DateTime>("AttemptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("attempted_at");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid")
                        .HasColumnName("channel_id");

                    b.Property<string>("ChannelType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("channel_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FailureReason")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("failure_reason");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_alert_deliveries");

                    b.HasIndex("AlertId")
                        .HasDatabaseName("i_x_alert_deliveries_alert_id");

                    b.HasIndex("AttemptedAt")
                        .HasDatabaseName("i_x_alert_deliveries_attempted_at");

                    b.HasIndex("ChannelId")
                        .HasDatabaseName("i_x_alert_deliveries_channel_id");

                    b.HasIndex("ChannelType")
                        .HasDatabaseName("i_x_alert_deliveries_channel_type");

                    b.HasIndex("Status")
                        .HasDatabaseName("i_x_alert_deliveries_status");

                    b.ToTable("alert_deliveries", (string)null);
                });

            modelBuilder.Entity("LowCortisol.Platform.API.Notification.Domain.Model.Entities.IncidentAction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("action_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(520)
                        .HasColumnType("character varying(520)")
                        .HasColumnName("description");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("performed_at");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasColumnName("performed_by");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_incident_actions");

                    b.HasIndex("ActionType")
                        .HasDatabaseName("i_x_incident_actions_action_type");

                    b.HasIndex("IncidentId")
                        .HasDatabaseName("i_x_incident_actions_incident_id");

                    b.HasIndex("PerformedAt")
                        .HasDatabaseName("i_x_incident_actions_performed_at");

                    b.ToTable("incident_actions", (string)null);
                });

            modelBuilder.Entity("LowCortisol.Platform.API.Notification.Domain.Model.Entities.IncidentAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<string>("AssigneeId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("assignee_id");

                    b.Property<string>("AssigneeName")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasColumnName("assignee_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_incident_assignments");

                    b.HasIndex("AssignedAt")
                        .HasDatabaseName("i_x_incident_assignments_assigned_at");

                    b.HasIndex("AssigneeId")
                        .HasDatabaseName("i_x_incident_assignments_assignee_id");

                    b.HasIndex("IncidentId")
                        .HasDatabaseName("i_x_incident_assignments_incident_id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("i_x_incident_assignments_is_active");

                    b.ToTable("incident_assignments", (string)null);
                });

            modelBuilder.Entity("LowCortisol.Platform.API.Workplace.Domain.Model.Aggregates.Site", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_sites");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("i_x_sites_created_at");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("i_x_sites_name");

                    b.HasIndex("Status")
                        .HasDatabaseName("i_x_sites_status");

                    b.ToTable("sites", (string)null);
                });

            modelBuilder.Entity("LowCortisol.Platform.API.Workplace.Domain.Model.Entities.DeviceGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("resource_type");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_device_groups");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("i_x_device_groups_created_at");

                    b.HasIndex("ResourceType")
                        .HasDatabaseName("i_x_device_groups_resource_type");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("i_x_device_groups_room_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("i_x_device_groups_status");

                    b.HasIndex("RoomId", "Name")
                        .IsUnique()
                        .HasDatabaseName("i_x_device_groups_room_id_name");

                    b.ToTable("device_groups", (string)null);
                });

            modelBuilder.Entity("LowCortisol.Platform.API.Workplace.Domain.Model.Entities.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_rooms");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("i_x_rooms_created_at");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("i_x_rooms_site_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("i_x_rooms_status");

                    b.HasIndex("SiteId", "Name")
                        .IsUnique()
                        .HasDatabaseName("i_x_rooms_site_id_name");

                    b.ToTable("rooms", (string)null);
                });

            modelBuilder.Entity("LowCortisol.Platform.API.DeviceControl.Domain.Model.Entities.CommandAuditEntry", b =>
                {
                    b.HasOne("LowCortisol.Platform.API.DeviceControl.Domain.Model.Aggregates.DeviceCommand", null)
                        .WithMany("AuditEntries")
                        .HasForeignKey("DeviceCommandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_command_audit_entries_device_commands_device_command_id");
                });

            modelBuilder.Entity("LowCortisol.Platform.API.DeviceControl.Domain.Model.Entities.CommandExecution", b =>
                {
                    b.HasOne("LowCortisol.Platform.API.DeviceControl.Domain.Model.Aggregates.DeviceCommand", null)
                        .WithMany("Executions")
                        .HasForeignKey("DeviceCommandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_command_executions_device_commands_device_command_id");
                });

            modelBuilder.Entity("LowCortisol.Platform.API.Notification.Domain.Model.Aggregates.Alert", b =>
                {
                    b.OwnsOne("LowCortisol.Platform.API.Notification.Domain.Model.ValueObjects.AlertMessage", "Message", b1 =>
                        {
                            b1.Property<Guid>("AlertId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(520)
                                .HasColumnType("character varying(520)")
                                .HasColumnName("description");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(160)
                                .HasColumnType("character varying(160)")
                                .HasColumnName("title");

                            b1.HasKey("AlertId")
                                .HasName("p_k_alerts");

                            b1.ToTable("alerts");

                            b1.WithOwner()
                                .HasForeignKey("AlertId")
                                .HasConstraintName("f_k_alerts_alerts_id");
                        });

                    b.OwnsOne("LowCortisol.Platform.API.Notification.Domain.Model.ValueObjects.ResponseSla", "ResponseSla", b1 =>
                        {
                            b1.Property<Guid>("AlertId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("MinutesToAcknowledge")
                                .HasColumnType("integer")
                                .HasColumnName("sla_minutes_to_acknowledge");

                            b1.Property<int>("MinutesToResolve")
                                .HasColumnType("integer")
                                .HasColumnName("sla_minutes_to_resolve");

                            b1.HasKey("AlertId")
                                .HasName("p_k_alerts");

                            b1.ToTable("alerts");

                            b1.WithOwner()
                                .HasForeignKey("AlertId")
                                .HasConstraintName("f_k_alerts_alerts_id");
                        });

                    b.Navigation("Message")
                        .IsRequired();

                    b.Navigation("ResponseSla")
                        .IsRequired();
                });

            modelBuilder.Entity("LowCortisol.Platform.API.Notification.Domain.Model.Entities.AlertDelivery", b =>
                {
                    b.HasOne("LowCortisol.Platform.API.Notification.Domain.Model.Aggregates.Alert", null)
                        .WithMany("Deliveries")
                        .HasForeignKey("AlertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_alert_deliveries_alerts_alert_id");

                    b.OwnsOne("LowCortisol.Platform.API.Notification.Domain.Model.ValueObjects.AlertMessage", "Message", b1 =>
                        {
                            b1.Property<Guid>("AlertDeliveryId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(520)
                                .HasColumnType("character varying(520)")
                                .HasColumnName("message_description");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(160)
                                .HasColumnType("character varying(160)")
                                .HasColumnName("message_title");

                            b1.HasKey("AlertDeliveryId")
                                .HasName("p_k_alert_deliveries");

                            b1.ToTable("alert_deliveries");

                            b1.WithOwner()
                                .HasForeignKey("AlertDeliveryId")
                                .HasConstraintName("f_k_alert_deliveries_alert_deliveries_id");
                        });

                    b.OwnsOne("LowCortisol.Platform.API.Notification.Domain.Model.ValueObjects.Recipient", "Recipient", b1 =>
                        {
                            b1.Property<Guid>("AlertDeliveryId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("DisplayName")
                                .IsRequired()
                                .HasMaxLength(140)
                                .HasColumnType("character varying(140)")
                                .HasColumnName("recipient_display_name");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(160)
                                .HasColumnType("character varying(160)")
                                .HasColumnName("recipient_email");

                            b1.Property<string>("UserId")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)")
                                .HasColumnName("recipient_user_id");

                            b1.HasKey("AlertDeliveryId")
                                .HasName("p_k_alert_deliveries");

                            b1.ToTable("alert_deliveries");

                            b1.WithOwner()
                                .HasForeignKey("AlertDeliveryId")
                                .HasConstraintName("f_k_alert_deliveries_alert_deliveries_id");
                        });

                    b.Navigation("Message")
                        .IsRequired();

                    b.Navigation("Recipient")
                        .IsRequired();
                });

            modelBuilder.Entity("LowCortisol.Platform.API.Notification.Domain.Model.Entities.IncidentAction", b =>
                {
                    b.HasOne("LowCortisol.Platform.API.Notification.Domain.Model.Aggregates.Incident", null)
                        .WithMany("Actions")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_incident_actions_incidents_incident_id");
                });

            modelBuilder.Entity("LowCortisol.Platform.API.Notification.Domain.Model.Entities.IncidentAssignment", b =>
                {
                    b.HasOne("LowCortisol.Platform.API.Notification.Domain.Model.Aggregates.Incident", null)
                        .WithMany("Assignments")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_incident_assignments_incidents_incident_id");
                });

            modelBuilder.Entity("LowCortisol.Platform.API.Workplace.Domain.Model.Entities.DeviceGroup", b =>
                {
                    b.HasOne("LowCortisol.Platform.API.Workplace.Domain.Model.Entities.Room", null)
                        .WithMany("DeviceGroups")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_device_groups_rooms_room_id");
                });

            modelBuilder.Entity("LowCortisol.Platform.API.Workplace.Domain.Model.Entities.Room", b =>
                {
                    b.HasOne("LowCortisol.Platform.API.Workplace.Domain.Model.Aggregates.Site", null)
                        .WithMany("Rooms")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_rooms_sites_site_id");
                });

            modelBuilder.Entity("LowCortisol.Platform.API.DeviceControl.Domain.Model.Aggregates.DeviceCommand", b =>
                {
                    b.Navigation("AuditEntries");

                    b.Navigation("Executions");
                });

            modelBuilder.Entity("LowCortisol.Platform.API.Notification.Domain.Model.Aggregates.Alert", b =>
                {
                    b.Navigation("Deliveries");
                });

            modelBuilder.Entity("LowCortisol.Platform.API.Notification.Domain.Model.Aggregates.Incident", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("LowCortisol.Platform.API.Workplace.Domain.Model.Aggregates.Site", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("LowCortisol.Platform.API.Workplace.Domain.Model.Entities.Room", b =>
                {
                    b.Navigation("DeviceGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
